# Generated by Django 5.1.1 on 2024-10-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_product_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="inventory",
            field=models.PositiveIntegerField(),
        ),
    ]
