# Generated by Django 5.1.1 on 2024-10-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_product_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="promotions",
            field=models.ManyToManyField(blank=True, to="store.promotion"),
        ),
    ]
